name: '"iamlive" Action For GitHub Actions'
description: 'Capture the used AWS IAM permissions using client-side monitoring (CSM) from your GitHub actions workflow.'
branding:
  icon: 'cloud'
  color: 'orange'
author: Marco Franssen
inputs:
  iamlive-version:
    description: >-
      The iamlive version you want to use (defaults to v0.48.0).
    required: false
    default: v0.48.0
outputs:
  iamlive-version:
    description: 'The iamlive version that was installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
